dynaconf_merge=true

[service]
persistence =   "native_in_mem"

[service.paths]
worlds      = [ "@path ./worlds/" ]
client_dist =   "@path ./client/dist/"
story_media =   "@path ./data/media/"
docs        =   "@path ./docs/_build/"
user_data   =   "@path ./data/user/"
cache_data  =   "@path ./data/tmp/"
