name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Git LFS Pull
      run: git lfs pull

    - name: Get the current date
      id: date
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tangl-test:3.2-${{ steps.date.outputs.timestamp }}

    - name: Run the Docker image
      run: |
        docker run -d --name=tangl -p 8000:8000 tangl-test:3.2-${{ steps.date.outputs.timestamp }}
        sleep 10
        curl http://localhost:8000/api/v2/system/info
        docker stop tangl
